language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_1bc2a7cd1d09_key -iv $encrypted_1bc2a7cd1d09_iv -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package jacoco:report publish_if_tagged
after_success:
- bash <(curl -s https://codecov.io/bash)
git:
  depth: false
env:
  global:
  - secure: u2UTCrVehn4Vsodr5zMpsEKQ0E66cJ64Wvkk2bA132CeobY7w7pocWEql+zSeXXu2bJh7LLlmWXs2H4Lcok9FWIsGSUghXx8tAuORDwoU47EVlsEaawY1EroEDfasO4l1crwvsTd7AePAQ/WjSUOVdyReShBR4g7Sv7N6/vueNR9Epvz64BoyM9daV1cao0qZKnQ2d6QdaH/xKA2VXCB4UjsyEVOvrVokzOpYdOP3eytaZDHrzXesjxhvt3itLDeRPRswYg9GhXQ+6JjniFas9Wlq2M+tbTsBnfPHm4zACU+v+XaEBXK+7GyDUmpHixNzauCgT5TSd5MpIs/bwDCq4l786UiVQXX7LbQv5QZ+WXByyF9wy/S7JRCBVxw4gyysGvFiBx57jPvDeenFYF85MQUuR8LA7nvkP0HMvAXou2+QFOPZpasAUhgTcL6WRCzRZn/i+VFbKZx78togzi+zizJADHWdagj0KW/wgTyuG+Xcx/DErS2a1o11iq5PweJTF5mCL8w8cZ1aetqc6hC6699vH+rjMRTuZvHcQm1FuLYa13j38T2Q4RcTTXq1/LlDen76IFxRFwtaghiWeg4+Y1/BM5+kLn3FljV0FTb0gwGuKMdFActRNMMSGbpYG5dzSH6jKRjt0jcbCIiDhjx5uZ+f7dkmV5yoN/8l50/mP4=
  - secure: qIZ4ty7v37WYI1ZX0AJYaqPCmnaDNDpy0U3YZPHfGXU31zUKk3XFMFiJz9vMVVCZaPE7AKayxyczSN+hvFVZRQn1VjnNxSiJJi0CXotzERv+YJ9af9X0DWIMgufn5pifEdfuMbXJ/3EhufvmLWHcNvcZgrTYs39toU82Qb0jX8jU7LV6azK0Meovv+iRs0ZLOTh+1t2Wg4yaRNH7VADc9dSoz7OK64tbaZe73bDgZG8+ZWtEdRRmIeJaQudnOH7VCNB+3jkx1Eat42ZHa4x0pruNdHSG2Op3n3NrYla8f1uMZ2mD7KUZ6uUAzel2xnLYwvI/jE4B1fO0ijgU/Av00bF5IpUIIxdpli9LJC5qzwcgmSsYwi3JBLGPCZfNkcS5QQJvGmuye+GIejRlcpcPX43/uGknsMlTio6rdYnRevZc0Nah1OOeTwV9+SotSwvB/JtH4XdJSbJc9pTc06fd5ouTw7qmJA8QoPeAuJ6/gCgZt+TsYfU/G9/sVgNMItqPZEyX9hq4rKGkicL9e1S6kziwVovIMdfqALORvu3dbPyPTuBKvXcg5R/4bf+FjJhIFZJDER6Ci3VsTwUHVTJW5eVfm5ANDXM1MnDHTXojOWuzkFiwHKwy2znmu7CTUSRaXg7td/E+14U/TCFnOGv7j/4Bj818V/I1FN5+PY1QoaY=
  - secure: Tdy3JYjaUc2r4mpVFKs9JUAjJJ5H8olOTxKicTepgjiYlqKLkk865QiQGnw6QW5MCSjRa9ywRPHLdSGO6z+rHGkEofrhOqAJjSdxlV2cqFVANZQjAbRcr16SA3gLviu3zA61/PiHbO3LagkTSWW1AqPec7kkXYjxGc89Nexs3JCoZKFfH2fCs2bP6in6xn+6hLdPq++5W0ZB04cNnAKeF9lsax10OrXcy/exFGeOapNTj3yYkNmepAYClidtxk3ypU0RvLsEmKZzbj8/SmUejLPm8yROwDSiDZC/aEOjTRdWg3Upp4bcUAIUQE5j68TxlaRooQaxYbQiaF9uQZpmRkTcfJZZd+WGeuujhTGPrUfUXnnMZias/tToACVpb0ilvZZHxlF1EnPpcCCAJ8n39XJ5O55mzBVa3u83scBR0VvKFqMfOnUp59DLo9jlt8+TVSb61iJIngzciLNX/i1TgAbzF5LomxLMKZIQOB93lJUXm3eVCzy8urkQVuPoRlV0ffrKuxVPpQXmlP2V27x6/Qv/6pq1+0d3ee3jMjfgSrTNak/IWQFVVDQR3IqwxyrSIv++im2SkWaBqKq799I8699RdhZ2kJZc6zEByQ9EAFgD222HCMSptZhuhLlOIvxMf9HSAX92JFd4Eqnwx/l6cUePgOUXhmmaxbpPX8Jt4lw=
