repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  braincheck: org.realityforge.braincheck:braincheck:jar:1.30.0

  testng: org.testng:testng:jar:6.11
